In [3]:
# Import the NumPy library
# NumPy provides high-performance structures for numerical operations, like vectors and matrices.
# It is preferred over normal python data structures because its implementations are much faster.
import numpy as np

### 1. Numpy array basics

In [4]:
# Creating Arrays from a Python list
vector = np.array([10, 20, 30, 40]) # 1D Array (Vector)
print("1D Vector:", vector)

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
]) # 2D Array (Matrix: 2 rows, 3 columns)
print("\n2D Matrix:\n", matrix)

# Arrays for initialization
zeros_matrix = np.zeros((3, 2)) # 3 rows, 2 columns of zeros
print("\nZeros Array:\n", zeros_matrix)
ones_vector = np.ones(5) # 5 elements of ones
print("\nOnes Vector:", ones_vector)

# Arrays with sequence
step_range = np.arange(0, 10, 3) # Start, Stop (exclusive), Step (0, 3, 6, 9)
print("\nRange Array (0, 3, 6, 9):", step_range)
equal_space = np.linspace(0, 1, 4) # 4 equally spaced points between 0 and 1
print("Linspace Array (4 points):", equal_space)

# Random arrays (Used heavily in simulations)
random_uniform = np.random.rand(3, 3) # 3x3 array of random floats between 0 and 1 (from a uniform distribution)
print("Random Array (Uniform 3x3):\n", random_uniform)

# Key Attributes
print("\nMatrix Shape (rows, cols):", matrix.shape)
print("Matrix Total Elements:", matrix.size)
print("Matrix Data Type (must be homogenous):", matrix.dtype)
print("Matrix Number of Dimensions:", matrix.ndim)


1D Vector: [10 20 30 40]

2D Matrix:
 [[1 2 3]
 [4 5 6]]

Zeros Array:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

Ones Vector: [1. 1. 1. 1. 1.]

Range Array (0, 3, 6, 9): [0 3 6 9]
Linspace Array (4 points): [0.         0.33333333 0.66666667 1.        ]
Random Array (Uniform 3x3):
 [[0.94265778 0.93976811 0.13471274]
 [0.18944686 0.5561892  0.04591453]
 [0.2831374  0.63712266 0.14634741]]

Matrix Shape (rows, cols): (2, 3)
Matrix Total Elements: 6
Matrix Data Type (must be homogenous): int64
Matrix Number of Dimensions: 2


### 2. Indexing and Slicing

In [5]:
arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 30, 90]
])

# Indexing (using [row, col]) (zero based indexes)
print("Element at row 1, col 2 (60):", arr[1, 2])

# Slicing
print("\nLast Row (all columns):", arr[-1, :])
print("Middle Column (all rows):", arr[:, 1])
print("Top-Left 2x2 Sub-array:\n", arr[:2, :2]) # Up to Row 2, Up to Col 2 

# Boolean Indexing (Masking)
mask = arr > 50
print("\nBoolean Mask (True where > 50):\n", mask)
print("Elements > 50:", arr[mask]) # Only returns elements where the mask is True

# Getting indices of true values
indices = np.where(arr == 30) # Returns a tuple of arrays: (row_indices, col_indices)
print("\nIndices of value 30:", indices)


Element at row 1, col 2 (60): 60

Last Row (all columns): [70 30 90]
Middle Column (all rows): [20 50 30]
Top-Left 2x2 Sub-array:
 [[10 20]
 [40 50]]

Boolean Mask (True where > 50):
 [[False False False]
 [False False  True]
 [ True False  True]]
Elements > 50: [60 70 90]

Indices of value 30: (array([0, 2]), array([2, 1]))


### 3. Element-wise Operations and Broadcasting

In [7]:
vec1 = np.array([5, 10, 15])
vec2 = np.array([1, 2, 3])

# Array-Array Operations (Element-wise)
print("Addition:", vec1 + vec2)
print("Division (Element-wise):", vec1 / vec2)
print("Squared value:", vec2 ** 2)

# Broadcasting (Array-Scalar Operations)
factor = 0.5
print("\nVector scaled by 0.5:", vec1 * factor)
print("Vector incremented by 1:", vec1 + 1)

# Some mathematical functions
print("\nNatural Log of vec2:", np.log(vec2))
print("Absolute value of a negative vector:", np.abs(np.array([-2, -5, 1])))
print("Square root:", np.sqrt(vec1))
print("Exponential:", np.exp(vec2))

Addition: [ 6 12 18]
Division (Element-wise): [5. 5. 5.]
Squared value: [1 4 9]

Vector scaled by 0.5: [2.5 5.  7.5]
Vector incremented by 1: [ 6 11 16]

Natural Log of vec2: [0.         0.69314718 1.09861229]
Absolute value of a negative vector: [2 5 1]
Square root: [2.23606798 3.16227766 3.87298335]
Exponential: [ 2.71828183  7.3890561  20.08553692]


### 4. Array Manipulation and Aggregation

In [8]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# Reshape (must maintain the original number of elements)
flat_array = matrix.reshape((6,)) # Flatten into 1D vector
print("Flattened Array:", flat_array)
reshaped_matrix = flat_array.reshape((3, 2)) # Reshape to 3 rows, 2 columns
print("\nReshaped (3x2) Matrix:\n", reshaped_matrix)

# Transpose (swapping rows and columns)
print("\nOriginal Matrix:\n", matrix)
print("Transposed Matrix (2x3 -> 3x2):\n", matrix.T)

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Stacking
stacked = np.vstack((arr1, arr2))  # Vertical stack
print("Stacked Vertically:\n", stacked)

hstacked = np.hstack((arr1, arr2))  # Horizontal stack
print("Stacked Horizontally:", hstacked)

# Splitting
split = np.split(arr2, 3)  # Split into 3 parts
print("Split Array:", split)

# Boolean indexing
arr = np.array([1, 2, 3, 4, 5, 6])
even = arr[arr % 2 == 0]
print("Even Numbers:", even)
# Masking is a common technique used
print("Masking:", arr % 2 == 0)

# Filtering
filtered = arr[arr > 3]
print("Numbers greater than 3:", filtered)

# Statistics
print("\nTotal Sum of all elements:", np.sum(matrix))
print("Mean (Average) of all elements:", np.mean(matrix))
print("Min value:", np.min(matrix))
print("Standard Deviation:", np.std(matrix))

# Statistics along an axis (0=columns, 1=rows)
print("\nSum along axis 0 (sum of each column):", np.sum(matrix, axis=0)) # [1+4, 2+5, 3+6]
print("Mean along axis 1 (average of each row):", np.mean(matrix, axis=1)) # Average of [1,2,3] and [4,5,6]


Flattened Array: [1 2 3 4 5 6]

Reshaped (3x2) Matrix:
 [[1 2]
 [3 4]
 [5 6]]

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed Matrix (2x3 -> 3x2):
 [[1 4]
 [2 5]
 [3 6]]
Stacked Vertically:
 [[1 2 3]
 [4 5 6]]
Stacked Horizontally: [1 2 3 4 5 6]
Split Array: [array([4]), array([5]), array([6])]
Even Numbers: [2 4 6]
Masking: [False  True False  True False  True]
Numbers greater than 3: [4 5 6]

Total Sum of all elements: 21
Mean (Average) of all elements: 3.5
Min value: 1
Standard Deviation: 1.707825127659933

Sum along axis 0 (sum of each column): [5 7 9]
Mean along axis 1 (average of each row): [2. 5.]


---

## NumPy assignment problems
#### Fill the TODOs in the respective assignments

In [10]:
# Assignment 1
'''
Create an array of 24 random (between 0 and 1 chosen from a uniform distribution) elements of shape (4, 6) and add the array [0.69, 0.96, -0.69, 0.22, 0.67, -0.76] to each row.
Then reshape it to a (3, 8) array and take its transpose. 
Find the locations where all elements are greater than the mean of the array and print it
'''
def assignment1():
    # TODO
    random_array = np.random.rand(4, 6)
    row = np.array([0.69, 0.96, -0.69, 0.22, 0.67, -0.76])
    add_array = random_array + row
    reshape_array = add_array.reshape((3, 8))
    transpose_array = reshape_array.T
    mean_array = np.mean(transpose_array)
    locations = np.where(transpose_array > mean_array)
    print(locations)
assignment1()

(array([0, 0, 1, 2, 2, 3, 3, 4, 4, 5, 6, 6, 7, 7]), array([0, 2, 0, 1, 2, 0, 2, 0, 1, 1, 0, 2, 0, 1]))


In [12]:
### Assignment 2: Normalization and Centering

'''
Objective: Create a standard normalized dataset from a specific random distribution.

1.  Read about Poisson Distributions and the corresponding NumPy function, np.random.poisson().
2.  Create a 1D NumPy array of 20 random integers modeling a Poisson distribution with lambda = 5.
3.  Center the data by subtracting its mean from every element.
4.  Normalize the centered data by dividing it by its standard deviation.
5.  Return the final centered and normalized array.
'''
def assignment2():
    # TODO
    poisson_array = np.random.poisson(lam = 5, size = 20)
    subtract_mean = poisson_array - np.mean(poisson_array)
    normalize = subtract_mean / np.std(subtract_mean)
    return normalize 
assignment2()

array([ 0.87832499, -1.26393109,  0.44987378,  0.02142256, -0.83547987,
        0.02142256, -0.40702866, -1.26393109, -0.83547987, -0.40702866,
        0.87832499,  0.44987378,  0.02142256,  0.44987378, -1.69238231,
        0.87832499,  0.02142256,  0.02142256,  3.02058108, -0.40702866])