# PyTorch Basics
This notebook covers the fundamental building block of PyTorch: **tensors**.
Think of a tensor as a fancy NumPy array that can also run on a GPU.

## 1. Creating Tensors
There are many ways to create tensors. Let's explore the most common ones.

In [1]:
import torch

# Creating a tensor from a Python list
t1 = torch.tensor([1.0, 2.0, 3.0])
print("From list:", t1)

# TODO: Create a tensor from the list [4.0, 5.0, 6.0] and print it
# YOUR CODE HERE
t2 = torch.tensor([4.0, 5.0, 6.0])
print("From list:", t2)


From list: tensor([1., 2., 3.])
From list: tensor([4., 5., 6.])


In [2]:
# Creating tensors filled with zeros or ones
zeros = torch.zeros(3, 4)   # 3 rows, 4 columns, all zeros
ones  = torch.ones(2, 3)    # 2 rows, 3 columns, all ones
print("Zeros:\n", zeros)
print("Ones:\n", ones)

# TODO: Create a 4x4 tensor filled with zeros and print its shape
# YOUR CODE HERE
zeros_4x4 = torch.zeros(4, 4)
print("Zeros\n", zeros_4x4)
print("Shape:", zeros_4x4.shape)

Zeros:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])
Zeros
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape: torch.Size([4, 4])


In [3]:
# Random tensors — very common in deep learning for weight initialisation
r = torch.rand(3, 3)   # values between 0 and 1
print("Random tensor:\n", r)

# TODO: Create a random tensor of shape (2, 5) and print it
# YOUR CODE HERE
a = torch.rand(2, 5)
print("Random tensor:\n", a)


Random tensor:
 tensor([[0.8754, 0.2733, 0.5135],
        [0.4207, 0.6043, 0.6254],
        [0.9967, 0.9197, 0.6742]])
Random tensor:
 tensor([[0.6000, 0.1316, 0.6325, 0.5257, 0.7739],
        [0.0220, 0.7771, 0.3252, 0.9632, 0.6938]])


## 2. Tensor Attributes
Every tensor has a shape, a dtype, and a device.

In [4]:
t = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

print("Shape  :", t.shape)
print("Dtype  :", t.dtype)
print("Device :", t.device)

# TODO: Create any tensor and print its shape, dtype, and device
# YOUR CODE HERE
t1 = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
print("Shape  :", t1.shape)
print("Dtype  :", t1.dtype)
print("Device :", t1.device)


Shape  : torch.Size([2, 2])
Dtype  : torch.float32
Device : cpu
Shape  : torch.Size([2, 3])
Dtype  : torch.float32
Device : cpu


## 3. Tensor Operations
Tensors support arithmetic just like NumPy arrays.

In [5]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

print("a + b =", a + b)
print("a * b =", a * b)
print("a - b =", a - b)

# TODO: Compute a / b and print the result
# YOUR CODE HERE
print("a / b =", a / b)


a + b = tensor([5., 7., 9.])
a * b = tensor([ 4., 10., 18.])
a - b = tensor([-3., -3., -3.])
a / b = tensor([0.2500, 0.4000, 0.5000])


In [6]:
# Matrix multiplication — you will use this constantly in Scribe
A = torch.rand(3, 4)
B = torch.rand(4, 2)
C = torch.matmul(A, B)   # or A @ B

print("A shape:", A.shape)
print("B shape:", B.shape)
print("C shape:", C.shape)   # should be (3, 2)

# TODO: Create two random matrices of shapes (5, 3) and (3, 6) and matrix-multiply them.
#       Print the shape of the result.
# YOUR CODE HERE
a = torch.rand(5, 3)
b = torch.rand(3, 6)
matmul = torch.matmul(a, b)
print("Matrix multiply Shape:", matmul.shape)

A shape: torch.Size([3, 4])
B shape: torch.Size([4, 2])
C shape: torch.Size([3, 2])
Matrix multiply Shape: torch.Size([5, 6])


## 4. Reshaping Tensors
`view` and `reshape` let you change the shape without changing the data.

In [8]:
t = torch.arange(12, dtype=torch.float32)   # [0, 1, 2, ..., 11]
print("Original:", t, "  shape:", t.shape)

t2d = t.view(3, 4)
print("Reshaped to (3, 4):\n", t2d)

# TODO: Reshape t into shape (2, 6) and print it
# YOUR CODE HERE
reshape = t.view(2, 6)
print("Reshaped to (2, 6):\n", reshape)


Original: tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])   shape: torch.Size([12])
Reshaped to (3, 4):
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
Reshaped to (2, 6):
 tensor([[ 0.,  1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10., 11.]])


## 5. Moving to GPU (optional)
If you have a GPU available, PyTorch can use it automatically.

In [9]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

t = torch.rand(3, 3)
t = t.to(device)
print("Tensor device:", t.device)

# TODO: Create a tensor of ones with shape (2, 2), move it to `device`, and print it
# YOUR CODE HERE
t1 = torch.rand(2, 2)
t1 = t1.to(device)
print("Tensor device:", t1.device)


Using device: cpu
Tensor device: cpu
Tensor device: cpu


## 6. Connecting to Scribe
In Scribe, every sketch stroke is stored as a tensor of shape `(seq_len, 5)` — one row per step, five values per step: `(Δx, Δy, p1, p2, p3)`.

In [11]:
# A tiny fake sketch: 4 steps, 5 values each
stroke = torch.tensor([
    [0.1,  0.2,  1, 0, 0],   # pen on paper, move right-down
    [0.05, 0.1,  1, 0, 0],
    [0.0,  0.0,  0, 1, 0],   # pen lifted
    [0.3,  0.0,  1, 0, 0],   # new stroke
], dtype=torch.float32)

print("Stroke tensor shape:", stroke.shape)
print("First step (Δx, Δy, pen states):", stroke[0])

# TODO: Print only the (Δx, Δy) columns of the stroke tensor (first two columns)
# Hint: use stroke[:, :2]
# YOUR CODE HERE
print("Δx, Δy columns:\n", stroke[:, :2])


Stroke tensor shape: torch.Size([4, 5])
First step (Δx, Δy, pen states): tensor([0.1000, 0.2000, 1.0000, 0.0000, 0.0000])
Δx, Δy columns:
 tensor([[0.1000, 0.2000],
        [0.0500, 0.1000],
        [0.0000, 0.0000],
        [0.3000, 0.0000]])


## Done!
You now know how to create, inspect, and manipulate tensors.
Next up: **autograd_training.ipynb** — how PyTorch learns from its mistakes.